### ISSUE TITLE
undefined method `kernel_driver_active?' for #<LIBUSB::Device 1/8 1f3a:efe8 ? ? ? (Vendor specific (ff,ff))>

### ISSUE THREAD

**Issue by G-S-E** [lolet/FELix#4]
Try to flash stock android image to cubieboard1 (A10) via

```
# ruby felix --tofes ~/android-tvbox-8188eu-cb1-nand-v2.2.img
```

Allways get an error

```
[FATAL] undefined method `kernel_driver_active?' for #<LIBUSB::Device 1/8 1f3a:efe8 ? ? ? (Vendor specific (ff,ff))>
```

I use (as host)

```
Linux odroidc2 3.14.79-odroidc2 #8 SMP PREEMPT Tue Sep 13 23:00:48 CEST 2016 aarch64 GNU/Linux
```

with ruby2.1 and  Gemfile modified to 

```
source "https://rubygems.org"
ruby "2.1.5"

gem 'hex_string'
gem 'hexdump'
gem 'colorize'
gem 'libusb'
gem 'bindata'
gem 'crc32'
gem 'inifile'
gem 'rc6'
```

Full output of the command:

```
# ruby felix --tofes ~/android-tvbox-8188eu-cb1-nand-v2.2.img
FELix 1.0 RC5 by Lolet
Warning: I don't give any warranty on this software. You use it at own risk!
────────────────────────────────────
* Connecting to device at port 1, FEL device 1@8 1f3a:efe8  [FATAL] undefined method `kernel_driver_active?' for #<LIBUSB::Device 1/8 1f3a:efe8 ? ? ? (Vendor specific (ff,ff))>
* Cleaning up                                               [OK]
```

**Comment by G-S-E** [comment]
```
# ruby felix --flash ~/android-tvbox-8188eu-cb1-nand-v2.2.img
```

give the same error at the output

**Comment by G-S-E** [comment]
Output of 

```
# ruby felix --image-info ~/android-tvbox-8188eu-cb1-nand-v2.2.img
```

is also strange for me

```
# ruby felix --image-info ~/android-tvbox-8188eu-cb1-nand-v2.2.img
Warning: Image is encrypted!
Decrypting...: 42/42
obj.magic does not have a :read_length parameter - returning empty string
/var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/base_primitive.rb:214:in `assert_value': value is '' but expected 'IMAGEWTY' for obj.magic (BinData::ValidityError)
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/base_primitive.rb:208:in `assert!'
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/base_primitive.rb:204:in `do_read'
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/struct.rb:138:in `block in do_read'
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/struct.rb:138:in `each'
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/struct.rb:138:in `do_read'
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/base.rb:147:in `block in read'
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/base.rb:253:in `call'
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/base.rb:253:in `start_read'
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/base.rb:145:in `read'
    from /var/lib/gems/2.1.0/gems/bindata-2.3.3/lib/bindata/base.rb:21:in `read'
    from /home/gse/Temp/FELix/FELHelpers.rb:304:in `show_image_info'
    from felix:428:in `block (2 levels) in <main>'
    from /usr/lib/ruby/2.1.0/optparse.rb:1359:in `call'
    from /usr/lib/ruby/2.1.0/optparse.rb:1359:in `block in parse_in_order'
    from /usr/lib/ruby/2.1.0/optparse.rb:1346:in `catch'
    from /usr/lib/ruby/2.1.0/optparse.rb:1346:in `parse_in_order'
    from /usr/lib/ruby/2.1.0/optparse.rb:1340:in `order!'
    from /usr/lib/ruby/2.1.0/optparse.rb:1432:in `permute!'
    from /usr/lib/ruby/2.1.0/optparse.rb:1454:in `parse!'
    from felix:571:in `<main>'

```

**Comment by jankowskib** [comment]
First problem has been fixed in https://github.com/Tigrouzen/FELix/commit/c3021ccccb3a962dedfb50515990920555215a23
Could you send me a link to firmware image?

**Comment by jankowskib** [comment]
OK. Fixed it now. Use bundler or downgrade manually gem bindata to 2.1.0
